name: trending crawler

on:
  schedule:
    # 早上8点执行
    - cron: '00 08 * * *'
    # 下午8点执行
    - cron: '00 20 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run github_trending
      run: |
        python github_trending.py
      env:
        secret_id: ${{ secrets.secret_id }}
        secret_key: ${{ secrets.secret_key }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
    - name: Commit and push changes back to the repository
      run: |
        git config --global user.email "fengxiaoyang163@163.com"
        git config --global user.name "fengyunzaidushi"
        git add data/github/*.json
        git add data/github/*.jsonl
        git commit -m "Update data from GitHub Actions"
        git push origin main
      env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GIT }}
